# name: Self-Hosted Runner Test

# on:
#   push:
#     branches:
#     - main

# jobs:
#   build:
#     runs-on: self-hosted
#     steps:
#     - uses: actions/checkout@v2

#     - name: docker build python
#       run: |
#         docker build ./python/introduction/ -t python:1.0.0
